/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;

import Entity.giaiThuongETT;
import BUS.giaiThuongBUS;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author Dat
 */
public class detailGiaiThuong extends javax.swing.JDialog {
    public giaiThuongETT giaithuong;

    public detailGiaiThuong(java.awt.Frame parent, boolean modal, giaiThuongETT data) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.giaithuong = data;

        // 1. Đổ dữ liệu vào các ô
        txtCCCD.setText(data.getCccd() != null ? data.getCccd() : "");
        cboCapGiai.setSelectedItem(data.getCapGiai());
        txtMaMon.setText(data.getMaMon() != null ? data.getMaMon() : "");
        cboLoaiGiai.setSelectedItem(data.getLoaiGiai());
        txtDiemCongCoMon.setText(data.getDiemCongCoMon() != null ? String.valueOf(data.getDiemCongCoMon()) : "0.0");
        txtDiemCongKhongMon.setText(data.getDiemCongKhongMon() != null ? String.valueOf(data.getDiemCongKhongMon()) : "0.0");

        // 2. KHÓA TOÀN BỘ Ô NHẬP LIỆU (Chỉ xem)
        txtCCCD.setEditable(false);
        btnChonCCCDThiSinh.setEnabled(false);
        txtMaMon.setEditable(false);
        btnChonMaMon.setEnabled(false);
        txtDiemCongCoMon.setEditable(false);
        txtDiemCongKhongMon.setEditable(false);
        cboCapGiai.setEnabled(false);
        cboLoaiGiai.setEnabled(false);

        // Đổi màu nền xám nhạt cho đồng bộ giao diện "chỉ đọc"
        java.awt.Color readOnlyColor = new java.awt.Color(246, 246, 246);
        txtCCCD.setBackground(readOnlyColor);
        txtMaMon.setBackground(readOnlyColor);
        txtDiemCongCoMon.setBackground(readOnlyColor);
        txtDiemCongKhongMon.setBackground(readOnlyColor);

        // Chỉnh màu nền cho ComboBox khi bị khóa (tránh bị xám mờ khó đọc)
        javax.swing.DefaultListCellRenderer renderer = new javax.swing.DefaultListCellRenderer() {
            @Override
            public void paint(java.awt.Graphics g) {
                setBackground(readOnlyColor);
                super.paint(g);
            }
        };
        cboCapGiai.setRenderer(renderer);
        cboLoaiGiai.setRenderer(renderer);

        // Ép focus vào nút thoát để tránh nháy con trỏ
        SwingUtilities.invokeLater(() -> {
            btnThoat1.requestFocusInWindow();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnChonCCCDThiSinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        btnChonMaMon = new javax.swing.JButton();
        cboLoaiGiai = new javax.swing.JComboBox<>();
        txtDiemCongCoMon = new javax.swing.JTextField();
        txtDiemCongKhongMon = new javax.swing.JTextField();
        cboCapGiai = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnThoat1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết giải thưởng");

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Chi tiết Giải Thưởng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CT Giải Thưởng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CCCD Thí Sinh");

        txtCCCD.setBackground(new java.awt.Color(246, 246, 246));
        txtCCCD.addActionListener(this::txtCCCDActionPerformed);

        btnChonCCCDThiSinh.setText("...");
        btnChonCCCDThiSinh.setToolTipText("");
        btnChonCCCDThiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonCCCDThiSinh.addActionListener(this::btnChonCCCDThiSinhActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cấp Giải");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã môn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Loại giải");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Điểm cộng có môn");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Điểm cộng không môn");

        txtMaMon.setBackground(new java.awt.Color(246, 246, 246));
        txtMaMon.addActionListener(this::txtMaMonActionPerformed);

        btnChonMaMon.setText("...");
        btnChonMaMon.setToolTipText("");
        btnChonMaMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaMon.addActionListener(this::btnChonMaMonActionPerformed);

        cboLoaiGiai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giải Nhất", "Giải Nhì", "Giải Ba", "Giải Khuyễn khích" }));
        cboLoaiGiai.addActionListener(this::cboLoaiGiaiActionPerformed);

        txtDiemCongCoMon.setBackground(new java.awt.Color(246, 246, 246));
        txtDiemCongCoMon.addActionListener(this::txtDiemCongCoMonActionPerformed);

        txtDiemCongKhongMon.setBackground(new java.awt.Color(246, 246, 246));
        txtDiemCongKhongMon.addActionListener(this::txtDiemCongKhongMonActionPerformed);

        cboCapGiai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quốc gia", "Tỉnh" }));
        cboCapGiai.addActionListener(this::cboCapGiaiActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(cboLoaiGiai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiemCongCoMon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtDiemCongKhongMon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(cboCapGiai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonCCCDThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonCCCDThiSinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCapGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonMaMon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboLoaiGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemCongCoMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiemCongKhongMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lý CT Giải Thưởng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");

        btnThoat1.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat1.addActionListener(this::btnThoat1ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void cboLoaiGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiGiaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiGiaiActionPerformed

    private void txtDiemCongCoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCongCoMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemCongCoMonActionPerformed

    private void txtDiemCongKhongMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCongKhongMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemCongKhongMonActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    private void cboCapGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCapGiaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCapGiaiActionPerformed

    private void btnChonCCCDThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCCCDThiSinhActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SELECT_GUI.selectThiSinh dialog = new SELECT_GUI.selectThiSinh(topFrame, true);
        dialog.setVisible(true);

        if (dialog.getXacNhan()) {
            txtCCCD.setText(dialog.getThiSinh().getCccd());
        }
    }//GEN-LAST:event_btnChonCCCDThiSinhActionPerformed

    private void btnChonMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaMonActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        SELECT_GUI.selectMon dialog = new SELECT_GUI.selectMon(topFrame, true);
        dialog.setVisible(true);

        if (dialog.getXacNhan()) {
            txtMaMon.setText(dialog.getMaMon()); 
        }
    }//GEN-LAST:event_btnChonMaMonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCCCDThiSinh;
    private javax.swing.JButton btnChonMaMon;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JComboBox<String> cboCapGiai;
    private javax.swing.JComboBox<String> cboLoaiGiai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiemCongCoMon;
    private javax.swing.JTextField txtDiemCongKhongMon;
    private javax.swing.JTextField txtMaMon;
    // End of variables declaration//GEN-END:variables
}
