/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;

/**
 *
 * @author mhoang
 */
public class excelNguyenVong extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(excelNguyenVong.class.getName());

    /**
     * Creates new form deleteNguyenVong
     */
    public boolean xacNhanImport = false, xacNhanExport = false, xacNhanExportDSTrungTuyen = false, xacNhanExportSLPhuongThuc = false;
    public excelNguyenVong(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelExcel = new javax.swing.JLabel();
        groupBoxExcel = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnXuatDSTrungTuyen = new javax.swing.JButton();
        btnXuatSLPhuongThuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xóa nguyện vọng");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        labelExcel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelExcel.setText("Excel Nguyện Vọng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelExcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(labelExcel)
                .addGap(21, 21, 21))
        );

        groupBoxExcel.setBackground(new java.awt.Color(255, 255, 255));
        groupBoxExcel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thực hiện excel table...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnExport.setBackground(new java.awt.Color(102, 102, 255));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setText("Export");
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.addActionListener(this::btnExportActionPerformed);

        btnImport.setBackground(new java.awt.Color(255, 255, 204));
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImport.setText("Import");
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.addActionListener(this::btnImportActionPerformed);

        btnXuatDSTrungTuyen.setBackground(new java.awt.Color(255, 255, 204));
        btnXuatDSTrungTuyen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatDSTrungTuyen.setText("DS TT");
        btnXuatDSTrungTuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDSTrungTuyen.addActionListener(this::btnXuatDSTrungTuyenActionPerformed);

        btnXuatSLPhuongThuc.setBackground(new java.awt.Color(102, 102, 255));
        btnXuatSLPhuongThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatSLPhuongThuc.setText("SL PT");
        btnXuatSLPhuongThuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatSLPhuongThuc.addActionListener(this::btnXuatSLPhuongThucActionPerformed);

        javax.swing.GroupLayout groupBoxExcelLayout = new javax.swing.GroupLayout(groupBoxExcel);
        groupBoxExcel.setLayout(groupBoxExcelLayout);
        groupBoxExcelLayout.setHorizontalGroup(
            groupBoxExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupBoxExcelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(groupBoxExcelLayout.createSequentialGroup()
                .addGroup(groupBoxExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupBoxExcelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnXuatDSTrungTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnXuatSLPhuongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groupBoxExcelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        groupBoxExcelLayout.setVerticalGroup(
            groupBoxExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupBoxExcelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(groupBoxExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(groupBoxExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatDSTrungTuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatSLPhuongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groupBoxExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupBoxExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        xacNhanExport = true;
        dispose();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        xacNhanExport = false;
        xacNhanImport = false;
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        xacNhanImport = true;
        dispose();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnXuatDSTrungTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSTrungTuyenActionPerformed
        // TODO add your handling code here:
        xacNhanExportDSTrungTuyen = true;
        dispose();
    }//GEN-LAST:event_btnXuatDSTrungTuyenActionPerformed

    private void btnXuatSLPhuongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatSLPhuongThucActionPerformed
        // TODO add your handling code here:
        xacNhanExportSLPhuongThuc = true;
        dispose();
    }//GEN-LAST:event_btnXuatSLPhuongThucActionPerformed

    public boolean getXacNhanImport()
    {
        return xacNhanImport;
    }
    
    public boolean getXacNhanExport()
    {
        return xacNhanExport;
    }
    
    public boolean getXacNhanExportDSTrungTuyen()
    {
        return xacNhanExportDSTrungTuyen;
    }
    
    public boolean getXacNhanExportSLPhuongThuc()
    {
        return xacNhanExportSLPhuongThuc;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExport;
    public javax.swing.JButton btnImport;
    public javax.swing.JButton btnThoat;
    public javax.swing.JButton btnXuatDSTrungTuyen;
    public javax.swing.JButton btnXuatSLPhuongThuc;
    public javax.swing.JPanel groupBoxExcel;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelExcel;
    // End of variables declaration//GEN-END:variables
}
