/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;
import BUS.nganhToHopBUS;
import Entity.diemCongETT;
import Entity.toHopETT;
import Entity.chungChiETT;
import BUS.diemCongBUS;
import Entity.nganhETT;
import Entity.giaiThuongETT;
import Entity.thiSinhXetTuyenETT;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import SELECT_GUI.selectThiSinh;
import SELECT_GUI.selectToHop;
import SELECT_GUI.selectNganh;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author LE MINH HUY
 */
public class insertDiemCong extends javax.swing.JDialog {
    private diemCongETT dc;
    private boolean xacNhan = false;
    public String phuongThuc;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(insertDiemCong.class.getName());
    private Entity.toHopETT toHopMonDaChon;
    public String cccd;
    public String toHopMon;
    public String maNganh;
    /**
     * Creates new form insertDiemCong
     */
    public insertDiemCong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Thêm Điểm Cộng");
        setLocationRelativeTo(parent);
        // Bind thủ công vì NetBeans không tự sinh cho cboPT
        cboPT.addActionListener(this::cboPTActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNganh = new javax.swing.JTextField();
        btnChonCCCD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnChonMaNganh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiemCC = new javax.swing.JTextField();
        txtMaToHop = new javax.swing.JTextField();
        btnChonMaToHop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDiemUTXT = new javax.swing.JTextField();
        txtDiemTong = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboPT = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Điểm Cộng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã ngành (*) :");

        txtMaNganh.setEditable(false);
        txtMaNganh.addActionListener(this::txtMaNganhActionPerformed);

        btnChonCCCD.setText("...");
        btnChonCCCD.setToolTipText("");
        btnChonCCCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonCCCD.addActionListener(this::btnChonCCCDActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CCCD:");

        txtCCCD.setEditable(false);
        txtCCCD.addActionListener(this::txtCCCDActionPerformed);

        btnChonMaNganh.setText("...");
        btnChonMaNganh.setToolTipText("");
        btnChonMaNganh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaNganh.addActionListener(this::btnChonMaNganhActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã tổ hợp:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Điểm CC:");

        txtDiemCC.setEditable(false);

        txtMaToHop.setEditable(false);
        txtMaToHop.addActionListener(this::txtMaToHopActionPerformed);

        btnChonMaToHop.setText("...");
        btnChonMaToHop.setToolTipText("");
        btnChonMaToHop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaToHop.addActionListener(this::btnChonMaToHopActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Phương thức:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Điểm UTXT :");

        txtDiemUTXT.setEditable(false);

        txtDiemTong.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Điểm tổng:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ghi chú:");

        cboPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xét THPT", "ĐGNL HCM", "Đánh giá V-SAT", "Tuyển Thẳng" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtDiemTong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemUTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboPT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonCCCD)
                    .addComponent(jLabel2)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonMaNganh)
                    .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonMaToHop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiemUTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lý thêm điểm cộng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(this::btnThemActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Thêm Điểm Cộng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(93, 93, 93))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNganhActionPerformed
        // TODO add your handling code here:            
    }//GEN-LAST:event_txtMaNganhActionPerformed

    private void btnChonCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCCCDActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        SELECT_GUI.selectThiSinh dialog = new SELECT_GUI.selectThiSinh(topFrame, true);
        dialog.setVisible(true);
        if (dialog.getXacNhan()) {
            Entity.thiSinhXetTuyenETT thiSinh = dialog.getThiSinh();
            this.cccd = thiSinh.getCccd();
            txtCCCD.setText(this.cccd);
            capNhatDiemTuDong();
        }
    }//GEN-LAST:event_btnChonCCCDActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void btnChonMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaNganhActionPerformed
        // TODO add your handling code here:
          JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectNganh dialog = new selectNganh(topFrame, true);
        dialog.setVisible(true);
        if(dialog.getXacNhan())
        {
            nganhETT nganh = dialog.getNganh();
            maNganh = nganh.getManganh();
            txtMaNganh.setText(maNganh);
            capNhatDiemTuDong(); 
        }
    }//GEN-LAST:event_btnChonMaNganhActionPerformed

    private void txtMaToHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaToHopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaToHopActionPerformed

    private void btnChonMaToHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaToHopActionPerformed
        // TODO add your handling code here:
         JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectToHop dialog = new selectToHop(topFrame, true);
        dialog.setVisible(true);
        if(dialog.getXacNhan())
        {
            toHopMonDaChon = dialog.getToHopETT();
            toHopETT toHopETT = dialog.getToHopETT();
            toHopMon = toHopETT.getMatohop();
            txtMaToHop.setText(toHopMon);     
            capNhatDiemTuDong(); 
        }
    }//GEN-LAST:event_btnChonMaToHopActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        xacNhan = false;
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         if (!kiemTraHopLe()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }

    try {
        diemCongETT dcNew = new diemCongETT();

        // ===== 1. THÔNG TIN =====
        dcNew.setTsCccd(txtCCCD.getText().trim());
        dcNew.setMaNganh(txtMaNganh.getText().trim());
        dcNew.setMaToHop(txtMaToHop.getText().trim());
        dcNew.setPhuongThuc(cboPT.getSelectedItem().toString());
        dcNew.setGhiChu(txtGhiChu.getText().trim());

        // ===== 2. ĐIỂM =====
        double dCC = txtDiemCC.getText().isEmpty() ? 0 : Double.parseDouble(txtDiemCC.getText());

        double dUT = 0;
        try {
             dUT = txtDiemUTXT.getText().isEmpty() ? 0 : Double.parseDouble(txtDiemUTXT.getText());
        } catch (Exception e) {
            dUT = 0;
        }

        double dTong = txtDiemTong.getText().isEmpty() ? 0 : Double.parseDouble(txtDiemTong.getText());

        dcNew.setDiemCC(dCC);
        dcNew.setDiemUtxt(dUT);
        dcNew.setDiemTong(dTong); // 🔥 QUAN TRỌNG

        // ===== 3. KEY =====
        dcNew.setDcKeys(
            txtCCCD.getText().trim() + "_" +
            txtMaNganh.getText().trim() + "_" +
            txtMaToHop.getText().trim() + "_" +
            cboPT.getSelectedItem().toString()
        );

        // ===== 4. GỌI BUS (CHUẨN MVC) =====
        diemCongBUS bus = new diemCongBUS();
        diemCongETT existing = bus.layDiemCongChinhXac(
            txtCCCD.getText().trim(),
            txtMaNganh.getText().trim(),
            txtMaToHop.getText().trim(),
            cboPT.getSelectedItem().toString()
        );

        if (existing != null) {
            JOptionPane.showMessageDialog(this, "Dữ liệu đã tồn tại!");
            return;
        }
         boolean saveOK = bus.themDiemCong(dcNew);
        if (saveOK) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            this.dc = dcNew;
            xacNhan = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi dữ liệu!");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed
     private void cboPTActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        String phuongThuc = cboPT.getSelectedItem().toString();
         capNhatDiemTuDong();  
    }                   
    public void capNhatDiemTuDong() {
        if (cccd == null || cccd.trim().isEmpty()) return;

        // === CÁC BIẾN TÍNH TOÁN ===
        double diemCC_de_ThayThe = 0.0; // Điểm quy đổi chứng chỉ (để thay thế điểm thi môn Anh)
        double diemCC_de_Cong    = 0.0; // Điểm cộng từ chứng chỉ (IELTS/ngoại ngữ)
        double diemGT_de_Cong    = 0.0; // Điểm cộng từ giải thưởng

        try (org.hibernate.Session session = CONFIG.HibernateUtil.getSessionFactory().openSession()) {

            // 1. LẤY ĐIỂM CHỨNG CHỈ: diem_quydoi (thay thế môn Anh) + diem_cong (cộng thêm nếu không thay thế)
            String sqlCC = "SELECT diem_quydoi, diem_cong FROM xt_chungchi WHERE cccd = :cccd LIMIT 1";
            Object[] ccData = (Object[]) session.createNativeQuery(sqlCC).setParameter("cccd", cccd).uniqueResult();
            if (ccData != null) {
                diemCC_de_ThayThe = ((Number) ccData[0]).doubleValue(); // Điểm quy đổi (thay thế môn Anh)
                diemCC_de_Cong    = ((Number) ccData[1]).doubleValue(); // Điểm cộng thêm (IELTS bonus)
            }

            // 2. LẤY ĐIỂM GIẢI THƯỞNG
            String sqlGT = "SELECT ma_mon, diem_cong_co_mon, diem_cong_khong_mon " +
                           "FROM xt_giathuong WHERE TRIM(cccd) = TRIM(:cccd) LIMIT 1";
            Object[] gtData = (Object[]) session.createNativeQuery(sqlGT).setParameter("cccd", cccd).uniqueResult();

            // 3. KIỂM TRA TỔ HỢP VÀ TÍNH ĐIỂM GIẢI THƯỞNG
            boolean coMonAnh = false;
            if (toHopMonDaChon != null) {
                coMonAnh = "N1".equals(toHopMonDaChon.getMon1()) ||
                           "N1".equals(toHopMonDaChon.getMon2()) ||
                           "N1".equals(toHopMonDaChon.getMon3());

                if (gtData != null) {
                    String maMonGiai = (String) gtData[0];
                    double dCoMon    = ((Number) gtData[1]).doubleValue();
                    double dKhongMon = ((Number) gtData[2]).doubleValue();

                    boolean trungMon = maMonGiai != null && (
                        maMonGiai.equals(toHopMonDaChon.getMon1()) ||
                        maMonGiai.equals(toHopMonDaChon.getMon2()) ||
                        maMonGiai.equals(toHopMonDaChon.getMon3()));

                    diemGT_de_Cong = trungMon ? dCoMon : dKhongMon;
                }

                // 4. Nếu tổ hợp có N1 → chứng chỉ đã THAY THẾ vào điểm thi Anh
                //    → KHÔNG cộng thêm diem_cong nữa (tránh tính 2 lần)
                if (coMonAnh) {
                    diemCC_de_Cong = 0.0;
                }
            }

            System.out.println("[DiemCong] CCCD=[" + cccd + "] CC=" + diemCC_de_Cong
                + " GT=" + diemGT_de_Cong);

        } catch (Exception e) {
            e.printStackTrace();
        }

        // 5. HIỂN THỊ KẾT QUẢ LÊN FORM
        // Điểm CC = điểm chứng chỉ (IELTS/ngoại ngữ)
        txtDiemCC.setText(String.valueOf(diemCC_de_Cong));

        // Điểm UTXT = điểm giải thưởng
        txtDiemUTXT.setText(String.valueOf(diemGT_de_Cong));

        // Tổng = CC + UTXT, tối đa 3.0
        double tongCong = Math.min(diemCC_de_Cong + diemGT_de_Cong, 3.0);
        txtDiemTong.setText(String.valueOf(tongCong));
    }

// HÀM PHỤ ĐỂ FIX LỖI "cannot find symbol" CHO NÍ NÈ
private double layDiemTuEntity(Entity.diemThiETT dt, String maMon) {
    if (maMon == null || dt == null) return 0.0;
    // Ánh xạ các mã môn từ bảng xt_tohop_monthi sang các cột trong xt_diemthixettuyen
    switch (maMon) {
        case "TO": return dt.getTo() != null ? dt.getTo() : 0.0;
        case "VA": return dt.getVa() != null ? dt.getVa() : 0.0;
        case "LI": return dt.getLi() != null ? dt.getLi() : 0.0;
        case "HO": return dt.getHo() != null ? dt.getHo() : 0.0;
        case "SU": return dt.getSu() != null ? dt.getSu() : 0.0;
        case "DI": return dt.getDi() != null ? dt.getDi() : 0.0;
        case "SI": return dt.getSi() != null ? dt.getSi() : 0.0;
        case "N1": return dt.getN1Thi() != null ? dt.getN1Thi() : 0.0; // Điểm thi Anh
        default: return 0.0;
    }
}
    // Hàm bổ trợ lấy điểm từ Entity diemThi dựa trên mã môn (Toán, Lý, Hóa...)
    private double layDiemTheoMaMon(Entity.diemThiETT dt, String maMon) {
        if (maMon == null || dt == null) return 0.0;
        // Huy kiểm tra xem trong Entity diemThiETT dùng getTo() hay getT1() nhé
        switch (maMon) {
            case "TO": case "T1": return dt.getTo() != null ? dt.getTo() : 0.0;
            case "LI": case "L1": return dt.getLi() != null ? dt.getLi() : 0.0;
            case "HO": case "H1": return dt.getHo() != null ? dt.getHo() : 0.0;
            case "SI": case "S1": return dt.getSi() != null ? dt.getSi() : 0.0;
            case "SU": case "S2": return dt.getSu() != null ? dt.getSu() : 0.0;
            case "DI": case "D1": return dt.getDi() != null ? dt.getDi() : 0.0;
            case "VA": case "V1": return dt.getVa() != null ? dt.getVa() : 0.0;
            default: return 0.0;
        }
    }
    private boolean kiemTraHopLe() {
        if (txtCCCD.getText().trim().isEmpty()) return false;
        if (txtMaNganh.getText().trim().isEmpty()) return false;
        if (txtMaToHop.getText().trim().isEmpty()) return false;
        return true;
    }
    public diemCongETT getDiemCong() {
        return dc;
    }

    public boolean isXacNhan() {
        return xacNhan;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCCCD;
    private javax.swing.JButton btnChonMaNganh;
    private javax.swing.JButton btnChonMaToHop;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiemCC;
    private javax.swing.JTextField txtDiemTong;
    private javax.swing.JTextField txtDiemUTXT;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaNganh;
    private javax.swing.JTextField txtMaToHop;
    // End of variables declaration//GEN-END:variables
}
