/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;
import Entity.nguyenVongXetTuyenETT;
import Entity.thiSinhETT;
import Entity.toHopETT;
import Entity.diemCongETT;
import Entity.diemThiETT;
import BUS.nguyenVongXetTuyenBUS;
import BUS.nganhToHopBUS;
import BUS.diemThiBUS;
import BUS.diemCongBUS;
import BUS.chungChiBUS;
import BUS.giaiThuongBUS;
import BUS.nganhBUS;
import BUS.quyTacGiaiThuongBUS;
import BUS.thiSinhXetTuyenBUS;
import DAO.bangQuyDoiDAO;
import Entity.bangQuyDoiETT;
import Entity.nganhETT;
import Entity.thiSinhXetTuyenETT;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import SELECT_GUI.selectThiSinh;
import SELECT_GUI.selectToHop;
import SELECT_GUI.selectNganh;
import java.util.ArrayList;
/**
 *
 * @author mhoang
 */
public class insertNguyenVong extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(insertNguyenVong.class.getName());
    public boolean xacNhan = false;
    public nguyenVongXetTuyenETT nguyenVong;
    nguyenVongXetTuyenBUS bus = new nguyenVongXetTuyenBUS();
    public String cccd;
    public String toHopMon;
    public String maNganh;
    public double doLechDiem = 0.0;
    private Double diemUuTienGoc = null;
    
    public Entity.toHopETT toHopMonDaChon = null;
    /**
     * Creates new form insertNguyenVong
     */
    public insertNguyenVong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        btnChonCCCThiSinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaNganh = new javax.swing.JTextField();
        btnChonMaNganh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm nguyện vọng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm nguyện vọng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CCCD Thí sinh (*) : ");

        txtCCCD.setEditable(false);
        txtCCCD.addActionListener(this::txtCCCDActionPerformed);

        btnChonCCCThiSinh.setText("...");
        btnChonCCCThiSinh.setToolTipText("");
        btnChonCCCThiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonCCCThiSinh.addActionListener(this::btnChonCCCThiSinhActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã ngành (*) : ");

        txtMaNganh.setEditable(false);

        btnChonMaNganh.setText("...");
        btnChonMaNganh.setToolTipText("");
        btnChonMaNganh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaNganh.addActionListener(this::btnChonMaNganhActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonCCCThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonCCCThiSinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonMaNganh))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("asd");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lý thêm NV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(this::btnThemActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Thêm Nguyện Vọng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        xacNhan = false;
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
// 1. KIỂM TRA ĐẦU VÀO & TRÙNG NGÀNH
        String cccd = txtCCCD.getText().trim();
        String maNganh = txtMaNganh.getText().trim();
        if (cccd.isEmpty() || maNganh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn CCCD và Mã ngành!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        nguyenVongXetTuyenBUS nvBus = new nguyenVongXetTuyenBUS();
        if (nvBus.kiemTraTrungNganh(cccd, maNganh)) {
            JOptionPane.showMessageDialog(this, "Thí sinh này đã đăng ký nguyện vọng vào ngành " + maNganh + " rồi!", "Trùng nguyện vọng", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. KHỞI TẠO DỮ LIỆU
        int thuTuNV = nvBus.phatSinhThuTuNguyenVongMoi(cccd);
        String ketQuaNV = "Chờ xét";
        thiSinhXetTuyenBUS tsBus = new thiSinhXetTuyenBUS();
        diemThiBUS dtBus = new diemThiBUS();
        chungChiBUS ccBus = new chungChiBUS();
        giaiThuongBUS gtBus = new giaiThuongBUS();
        quyTacGiaiThuongBUS qtBus = new quyTacGiaiThuongBUS();
        nganhToHopBUS nthBus = new nganhToHopBUS();
        DAO.bangQuyDoiDAO qdDao = new DAO.bangQuyDoiDAO();

        qtBus.loadQuyTac();
        ArrayList<Entity.bangQuyDoiETT> dsQuyDoi = qdDao.layDanhSach();

        // 3. TÍNH ĐIỂM ƯU TIÊN GỐC (KHU VỰC + ĐỐI TƯỢNG)
        String khuVuc = tsBus.layKhuVucTheoCCCD(cccd);
        String doiTuong = tsBus.layDoiTuongTheoCCCD(cccd);
        double dKV = 0, dDT = 0;
        if (khuVuc != null) {
            if (khuVuc.contains("1")) dKV = 0.75;
            else if (khuVuc.contains("2-NT") || khuVuc.contains("2NT")) dKV = 0.5;
            else if (khuVuc.equals("KV2")) dKV = 0.25;
        }
        if (doiTuong != null) {
            if ("1234".contains(doiTuong.substring(doiTuong.length()-1))) dDT = 2.0;
            else if ("567".contains(doiTuong.substring(doiTuong.length()-1))) dDT = 1.0;
        }
        double diemUTQDGoc = dKV + dDT;

        // 4. LẤY ĐIỂM THI & IELTS
        diemThiETT diemThi = dtBus.layDiemTheoCCCD(cccd);
        double[] ielts = ccBus.layDiemIELTS(cccd);
        double dQDIelts = ielts != null ? ielts[0] : 0.0;
        double dCongIelts = ielts != null ? ielts[1] : 0.0;
        Object[] gtData = gtBus.layGiaiThuong(cccd);
        String[] ttGiai = gtBus.layCapVaLoaiGiai(cccd);

        int soDongLuuThanhCong = 0;
        nganhBUS nBus = new nganhBUS();
        String toHopGoc = "";
        for (Entity.nganhETT ng : nBus.layDanhSach()) {
            if (ng.getManganh().equals(maNganh)) { toHopGoc = ng.getN_tohopgoc(); break; }
        }

        // 🔥 CHIẾN DỊCH 1: XÉT TUYỂN THẲNG
        Entity.quyTacGiaiThuongETT quyTac = (ttGiai != null) ? qtBus.layQuyTac(ttGiai[0], ttGiai[1]) : null;
        if (quyTac != null && quyTac.getXetTuyenThang() == 1) {
            if (nvBus.themNguyenVong(createNguyenVong(cccd, maNganh, thuTuNV, "Xét tuyển thẳng", "Không", 30.0, 0.0, 0.0, 0.0, 30.0, ketQuaNV))) soDongLuuThanhCong++;
        }

        // 🔥 CHIẾN DỊCH 2: QUÉT TỔ HỢP (THPT, V-SAT, ĐGNL)
        if (diemThi != null) {
            ArrayList<Entity.toHopETT> dsToHop = nthBus.layDanhSachToHopTheoNganh(maNganh);
            for (Entity.toHopETT toHop : dsToHop) {
                String maTH = toHop.getMatohop(), m1 = toHop.getMon1(), m2 = toHop.getMon2(), m3 = toHop.getMon3();
                double d1 = layDiemTheoMaMon(diemThi, m1), d2 = layDiemTheoMaMon(diemThi, m2), d3 = layDiemTheoMaMon(diemThi, m3);

                // --- CHẶN ĐIỂM LIỆT (Sử dụng điểm thi thực tế) ---
                if (d1 <= 1.0 || d2 <= 1.0 || d3 <= 1.0) continue;

                // --- TÍNH ĐIỂM CỘNG KHUYẾN KHÍCH ---
                boolean coAnh = "N1".equals(m1) || "N1".equals(m2) || "N1".equals(m3);
                double dCong = Math.min((coAnh ? 0 : dCongIelts) + (gtData != null ? ((String)gtData[0]).matches(m1+"|"+m2+"|"+m3) ? (double)gtData[1] : (double)gtData[2] : 0), 3.0);
                
                double[] hs = nthBus.layHeSoMon(maNganh, maTH);
                double W = hs[0] + hs[1] + hs[2], doLech = nthBus.layDoLechDiem(maNganh, maTH);
                if (W <= 0) continue;

                // 🎯 2.1 XÉT THPT (ĐƯỢC BÙ IELTS)
                double d1_t = "N1".equals(m1) ? Math.max(d1, dQDIelts) : d1;
                double d2_t = "N1".equals(m2) ? Math.max(d2, dQDIelts) : d2;
                double d3_t = "N1".equals(m3) ? Math.max(d3, dQDIelts) : d3;
                
                if (d1_t <= 10 && d2_t <= 10 && d3_t <= 10) {
                    double thxt = Math.round(((d1_t*hs[0] + d2_t*hs[1] + d3_t*hs[2])/W)*300.0)/100.0;
                    double ut = (thxt + dCong >= 22.5) ? Math.round(((30-thxt-dCong)/7.5)*diemUTQDGoc*100.0)/100.0 : diemUTQDGoc;
                    if (nvBus.themNguyenVong(createNguyenVong(cccd, maNganh, thuTuNV, "Xét THPT", maTH, thxt, diemUTQDGoc, ut, dCong, Math.min(30.0, Math.round((thxt+ut+dCong+doLech)*100.0)/100.0), ketQuaNV))) soDongLuuThanhCong++;
                }

                // 🎯 2.2 V-SAT (KHÔNG BÙ IELTS - Lấy điểm d1, d2, d3 gốc)
                double v1 = CAL.AdmissionsConverter.quyDoiDiemChung("Đánh giá V-SAT", maTH, m1, d1, dsQuyDoi);
                double v2 = CAL.AdmissionsConverter.quyDoiDiemChung("Đánh giá V-SAT", maTH, m2, d2, dsQuyDoi);
                double v3 = CAL.AdmissionsConverter.quyDoiDiemChung("Đánh giá V-SAT", maTH, m3, d3, dsQuyDoi);
                double thxt_v = Math.round(((v1*hs[0] + v2*hs[1] + v3*hs[2])/W)*300.0)/100.0;
                if (thxt_v > 0) {
                    double ut_v = (thxt_v + dCong >= 22.5) ? Math.round(((30-thxt_v-dCong)/7.5)*diemUTQDGoc*100.0)/100.0 : diemUTQDGoc;
                    if (nvBus.themNguyenVong(createNguyenVong(cccd, maNganh, thuTuNV, "Đánh giá V-SAT", maTH, thxt_v, diemUTQDGoc, ut_v, dCong, Math.min(30.0, Math.round((thxt_v+ut_v+dCong+doLech)*100.0)/100.0), ketQuaNV))) soDongLuuThanhCong++;
                }

                // 🎯 2.3 ĐGNL (CHỈ TỔ HỢP GỐC)
                if (maTH.equals(toHopGoc)) {
                    double dNL = (diemThi.getNl1() != null) ? diemThi.getNl1() : 0.0;
                    double thxt_nl = Math.round(CAL.AdmissionsConverter.quyDoiDiemChung("ĐGNL HCM", maTH, "", dNL, dsQuyDoi)*100.0)/100.0;
                    if (thxt_nl > 0) {
                        double ut_nl = (thxt_nl + dCong >= 22.5) ? Math.round(((30-thxt_nl-dCong)/7.5)*diemUTQDGoc*100.0)/100.0 : diemUTQDGoc;
                        if (nvBus.themNguyenVong(createNguyenVong(cccd, maNganh, thuTuNV, "ĐGNL HCM", maTH, thxt_nl, diemUTQDGoc, ut_nl, dCong, Math.min(30.0, Math.round((thxt_nl+ut_nl+dCong)*100.0)/100.0), ketQuaNV))) soDongLuuThanhCong++;
                    }
                }
            }
        }

        if (soDongLuuThanhCong > 0) {
            xacNhan = true;
            nguyenVong = createNguyenVong(cccd, maNganh, thuTuNV, "", "", 0, 0, 0, 0, 0, "");
            JOptionPane.showMessageDialog(this, "Đã tự động lưu " + soDongLuuThanhCong + " phương thức xét tuyển!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Không đủ điều kiện xét tuyển!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

// 🚀 ĐÃ SỬA: Thêm tham số utqdGoc vào
    private nguyenVongXetTuyenETT createNguyenVong(String cccd, String maNganh, int thuTuNV, String phuongThuc, String toHop, double thxt, double utqdGoc, double utqdThucTe, double cong, double diemXT, String ketQua) {
        nguyenVongXetTuyenETT ct = new nguyenVongXetTuyenETT();
        ct.setNnCccd(cccd);
        ct.setNvMaNganh(maNganh);
        ct.setNvTt(thuTuNV);
        ct.setTtPhuongThuc(phuongThuc);
        ct.setTtThm(toHop);
        ct.setDiemThxt(thxt);
        
        // Gắn 2 loại điểm ưu tiên vào
        ct.setDiemUtqdGoc(utqdGoc);    // Điểm gốc để đối chứng
        ct.setDiemUtqd(utqdThucTe);    // Điểm thực tế sau khi bị bóp
        
        ct.setDiemCong(cong);
        ct.setDiemXetTuyen(diemXT);
        ct.setNvKetQua(ketQua);
        ct.setNvKeys(cccd + "_" + thuTuNV + "_" + phuongThuc + "_" + toHop); 
        return ct;
    }
    
    private void btnChonCCCThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCCCThiSinhActionPerformed
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectThiSinh dialog = new selectThiSinh(topFrame, true);
        dialog.setVisible(true);
        
        if(dialog.getXacNhan()) {
            thiSinhXetTuyenETT thiSinh = dialog.getThiSinh();
            cccd = thiSinh.getCccd();
            txtCCCD.setText(cccd);
        }
    }//GEN-LAST:event_btnChonCCCThiSinhActionPerformed

    private void btnChonMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaNganhActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectNganh dialog = new selectNganh(topFrame, true);
        dialog.setVisible(true);
        
        if(dialog.getXacNhan())
        {
            nganhETT nganh = dialog.getNganh();
            maNganh = nganh.getManganh();
            txtMaNganh.setText(maNganh);
        }
    }//GEN-LAST:event_btnChonMaNganhActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

     
// =====================================================================
    // HÀM PHỤ TRỢ: Lấy điểm chính xác dựa vào mã môn (Phiên bản Full Database)
    // =====================================================================
    private double layDiemTheoMaMon(diemThiETT dt, String maMon) {
        // Kiểm tra an toàn: Nếu mã môn rỗng thì trả về 0 luôn
        if (maMon == null || maMon.trim().isEmpty()) return 0.0;
        
        switch (maMon.toUpperCase()) {
            // --- 1. CÁC MÔN KHOA HỌC TỰ NHIÊN & XÃ HỘI ---
            case "TO": return dt.getTo() != null ? dt.getTo() : 0.0;      // Toán
            case "LI": return dt.getLi() != null ? dt.getLi() : 0.0;      // Lý
            case "HO": return dt.getHo() != null ? dt.getHo() : 0.0;      // Hóa
            case "SI": return dt.getSi() != null ? dt.getSi() : 0.0;      // Sinh
            case "VA": return dt.getVa() != null ? dt.getVa() : 0.0;      // Văn
            case "SU": return dt.getSu() != null ? dt.getSu() : 0.0;      // Sử
            case "DI": return dt.getDi() != null ? dt.getDi() : 0.0;      // Địa
            
            // --- 2. NGOẠI NGỮ (Tự động lấy điểm cao nhất giữa Thi và Quy đổi CC) ---
            case "N1": 
                double diemThiTA = dt.getN1Thi() != null ? dt.getN1Thi() : 0.0;
                double diemQuyDoiTA = dt.getN1Cc() != null ? dt.getN1Cc() : 0.0;
                return Math.max(diemThiTA, diemQuyDoiTA);
                
            // --- 3. CÁC MÔN CHƯƠNG TRÌNH MỚI 2018 ---
            case "KTPL": return dt.getKtpl() != null ? dt.getKtpl() : 0.0; // Kinh tế Pháp luật
            case "TI": return dt.getTi() != null ? dt.getTi() : 0.0;       // Tin học
            case "CNCN": return dt.getCncn() != null ? dt.getCncn() : 0.0; // Công nghệ Công nghiệp
            case "CNNN": return dt.getCnnn() != null ? dt.getCnnn() : 0.0; // Công nghệ Nông nghiệp
            
            // --- 4. CÁC MÔN NĂNG KHIẾU & ĐÁNH GIÁ NĂNG LỰC ---
            case "NK1": return dt.getNk1() != null ? dt.getNk1() : 0.0;    // Năng khiếu 1
            case "NK2": return dt.getNk2() != null ? dt.getNk2() : 0.0;    // Năng khiếu 2
            case "NK3": return dt.getNk3() != null ? dt.getNk3() : 0.0;
            case "NK4": return dt.getNk4() != null ? dt.getNk4() : 0.0;
            case "NK5": return dt.getNk5() != null ? dt.getNk5() : 0.0;
            case "NK6": return dt.getNk6() != null ? dt.getNk6() : 0.0;
            
            case "NL1": return dt.getNl1() != null ? dt.getNl1() : 0.0;    // ĐGNL HCM
            
            // --- DEFAULT: Trả về 0 nếu mã môn không khớp ---
            default: return 0.0; 
        }
    }
    
    public boolean kiemTraHopLe()
    {
        if(bus.kiemTraRong(txtCCCD.getText()))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống CCCD");
            txtCCCD.requestFocus();
            return false;
        }
        if(bus.kiemTraRong(txtMaNganh.getText()))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống Mã ngành");
            txtMaNganh.requestFocus();
            return false; 
        }
       return true;
    }
    
public boolean kiemTraTrungNguyenVong(String cccd, int thuTu, String maNganh, String phuongThuc, String toHop) {
        if (bus.ds == null) return true;

        for(nguyenVongXetTuyenETT ct : bus.ds) {
            // Chỉ kiểm tra đối với cùng 1 thí sinh (cùng CCCD)
            if (ct.getNnCccd().equals(cccd)) {
                
                // 🚨 LUẬT 1: Cấm trùng Thứ Tự NV nhưng cho ngành KHÁC.
                // Nếu DB đã có NV 1 cho ngành A, mà giờ ráng nhét NV 1 cho ngành B -> CHẶN
                if(ct.getNvTt() == thuTu && !ct.getNvMaNganh().equals(maNganh)) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Thí sinh đã đăng ký Nguyện vọng " + thuTu + " cho ngành khác (" + ct.getNvMaNganh() + ") rồi!\n" +
                        "Vui lòng chọn số thứ tự Nguyện vọng tiếp theo (Ví dụ: " + (thuTu + 1) + ").",
                        "Lỗi thứ tự nguyện vọng",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    return false;
                }
                
                // 🚨 LUẬT 2: Cấm trùng Y Hệt (Cùng Ngành + Cùng Phương thức)
                // Ví dụ DB đã có CNTT xét THPT rồi, giờ bấm Thêm nữa nó sẽ quét trúng và chặn.
                if(ct.getNvMaNganh().equals(maNganh) && ct.getTtPhuongThuc().equals(phuongThuc)) {
                    // Chỗ này không cần hiện JOptionPane vì trong vòng lặp quét 4 cái, hiện popup 4 lần sẽ gây khó chịu.
                    // Chỉ cần return false, vòng lặp ở nút Thêm sẽ tự động 'continue' bỏ qua dòng này.
                    System.out.println("⚠️ Bỏ qua: Đã tồn tại " + maNganh + " - " + phuongThuc);
                    return false;
                }
            }
        }
        return true;
    }
    
    public boolean xacNhanThem()
    {
        return xacNhan;
    }
    
    public nguyenVongXetTuyenETT getNguyenVong()
    {
        return nguyenVong;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCCCThiSinh;
    private javax.swing.JButton btnChonMaNganh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtMaNganh;
    // End of variables declaration//GEN-END:variables
}
