/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;
import Entity.diemCongETT;
import Entity.nganhETT;
import Entity.toHopETT;
import SELECT_GUI.selectNganh;
import SELECT_GUI.selectThiSinh;
import SELECT_GUI.selectToHop;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author LE MINH HUY
 */
    public class updateDiemCong extends javax.swing.JDialog {
        private diemCongETT dc;
        private boolean xacNhan = false;
        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(updateDiemCong.class.getName());
        private Entity.toHopETT toHopMonDaChon;
        public String cccd;
        public String toHopMon;
        public String maNganh;
        /**
         * Creates new form updateDiemCong
         */
       public updateDiemCong(java.awt.Frame parent, boolean modal, diemCongETT dc) {
        super(parent, modal);
        initComponents();

        this.dc = dc;

        // 🔥 gán biến
        this.cccd = dc.getTsCccd();
        this.maNganh = dc.getMaNganh();
        this.toHopMon = dc.getMaToHop();
        // 🔥 LOAD LẠI TỔ HỢP
        try (org.hibernate.Session session = CONFIG.HibernateUtil.getSessionFactory().openSession()) {
            String sql = "FROM toHopETT WHERE matohop = :matohop";
            toHopMonDaChon = session.createQuery(sql, Entity.toHopETT.class)
                    .setParameter("matohop", this.toHopMon)
                    .uniqueResult();
        }
        // 🔥 hiển thị dữ liệu lên form
        txtCccd.setText(cccd);
        txtMaNganh.setText(maNganh);
        txtMaToHop.setText(toHopMon);

        txtDiemCC.setText(String.valueOf(dc.getDiemCC()));
        txtDiemUTXT.setText(String.valueOf(dc.getDiemUtxt()));
        txtDiemTong.setText(String.valueOf(dc.getDiemTong())); // 🔥 thêm
        txtGhiChu.setText(dc.getGhiChu());

        // 🔥 set phương thức
        jComboBox1.setSelectedItem(dc.getPhuongThuc());

        // 🔥 mở ghi chú nhập tay
        txtGhiChu.setEditable(true);
        txtGhiChu.setEnabled(true);

        // 🔥 auto tính lại
        jComboBox1.addActionListener(e -> capNhatDiemTuDong());


        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNganh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCccd = new javax.swing.JTextField();
        btnChonMaNganh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiemCC = new javax.swing.JTextField();
        txtMaToHop = new javax.swing.JTextField();
        btnChonMaToHop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDiemUTXT = new javax.swing.JTextField();
        txtDiemTong = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Sửa Điểm Cộng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sửa Điểm Cộng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã ngành (*) :");

        txtMaNganh.setEditable(false);
        txtMaNganh.addActionListener(this::txtMaNganhActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CCCD:");

        txtCccd.setEditable(false);
        txtCccd.addActionListener(this::txtCCCDActionPerformed);

        btnChonMaNganh.setText("...");
        btnChonMaNganh.setToolTipText("");
        btnChonMaNganh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaNganh.addActionListener(this::btnChonMaNganhActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã tổ hợp:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Điểm CC:");

        txtDiemCC.setEditable(false);

        txtMaToHop.setEditable(false);
        txtMaToHop.addActionListener(this::txtMaToHopActionPerformed);

        btnChonMaToHop.setText("...");
        btnChonMaToHop.setToolTipText("");
        btnChonMaToHop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChonMaToHop.addActionListener(this::btnChonMaToHopActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Phương thức:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Điểm UTXT :");

        txtDiemUTXT.setEditable(false);

        txtDiemTong.setEditable(false);

        txtGhiChu.setFocusCycleRoot(true);
        txtGhiChu.addActionListener(this::txtGhiChuActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Điểm tổng:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Ghi chú:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xét THPT", "ĐGNL HCM", "Đánh giá V-SAT", "Tuyển Thẳng" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtDiemTong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCccd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemUTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChonMaNganh)
                    .addComponent(txtMaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaToHop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonMaToHop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiemUTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiemTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lý sửa điểm cộng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(this::btnSuaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNganhActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void btnChonMaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaNganhActionPerformed
        // TODO add your handling code here:
          JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectNganh dialog = new selectNganh(topFrame, true);
        dialog.setVisible(true);
        if(dialog.getXacNhan())
        {
            nganhETT nganh = dialog.getNganh();
            maNganh = nganh.getManganh();
            txtMaNganh.setText(maNganh);
            capNhatDiemTuDong(); 
        }
    }//GEN-LAST:event_btnChonMaNganhActionPerformed

    private void txtMaToHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaToHopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaToHopActionPerformed

    private void btnChonMaToHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonMaToHopActionPerformed
        // TODO add your handling code here:
           JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        selectToHop dialog = new selectToHop(topFrame, true);
        dialog.setVisible(true);
        if(dialog.getXacNhan())
        {
            toHopMonDaChon = dialog.getToHopETT();
            toHopETT toHopETT = dialog.getToHopETT();
            toHopMon = toHopETT.getMatohop();
            txtMaToHop.setText(toHopMon);     
            capNhatDiemTuDong(); 
        }
    }//GEN-LAST:event_btnChonMaToHopActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        xacNhan = false;
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
                                     
        try {
            dc.setTsCccd(txtCccd.getText().trim());
            dc.setMaNganh(txtMaNganh.getText().trim());
            dc.setMaToHop(txtMaToHop.getText().trim());
            dc.setPhuongThuc(jComboBox1.getSelectedItem().toString());

            // 🔥 GHI CHÚ
            dc.setGhiChu(txtGhiChu.getText().trim());

            double dCC = Double.parseDouble(txtDiemCC.getText().isEmpty() ? "0" : txtDiemCC.getText());
            double dUT = Double.parseDouble(txtDiemUTXT.getText().isEmpty() ? "0" : txtDiemUTXT.getText());
            double dTong = Double.parseDouble(txtDiemTong.getText().isEmpty() ? "0" : txtDiemTong.getText());

            dc.setDiemCC(dCC);
            dc.setDiemUtxt(dUT);
            dc.setDiemTong(dTong);

            // 🔥 UPDATE DB (QUAN TRỌNG NHẤT)
            org.hibernate.Session session = null;
            org.hibernate.Transaction tx = null;

            try {
                session = CONFIG.HibernateUtil.getSessionFactory().openSession();
                tx = session.beginTransaction();

                session.update(dc); // 🔥 BẮT BUỘC

                tx.commit();

            } catch (Exception e) {
                if (tx != null) tx.rollback();
                JOptionPane.showMessageDialog(this, "Lỗi cập nhật DB!");
                e.printStackTrace();
                return; // ❗ không đóng form nếu lỗi
            }

            xacNhan = true;
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không được đổi dữ liệu CCCD!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed
    public diemCongETT getDiemCong() {
        return dc;
    }
    public void capNhatDiemTuDong() {
        String cccd = txtCccd.getText().trim();
        if (cccd.isEmpty()) return;

        double diemCC = 0.0;
        double diemGT = 0.0;

        try (org.hibernate.Session session = CONFIG.HibernateUtil.getSessionFactory().openSession()) {

            // ===== 1. CHỨNG CHỈ =====
            String sqlCC = "SELECT diem_cong FROM xt_chungchi WHERE cccd = :cccd LIMIT 1";
            Object resCC = session.createNativeQuery(sqlCC)
                    .setParameter("cccd", cccd)
                    .uniqueResult();

            if (resCC != null) {
                diemCC = ((Number) resCC).doubleValue();
            }
            boolean coMonAnh = false;

            if (toHopMonDaChon != null) {
                String m1 = toHopMonDaChon.getMon1();
                String m2 = toHopMonDaChon.getMon2();
                String m3 = toHopMonDaChon.getMon3();

                coMonAnh = "N1".equals(m1) || "N1".equals(m2) || "N1".equals(m3);
            }

            // 🔥 nếu có tiếng Anh → KHÔNG cộng CC
            if (coMonAnh) {
                diemCC = 0;
            }
            // ===== 2. GIẢI THƯỞNG =====
            String sqlGT = "SELECT ma_mon, diem_cong_co_mon, diem_cong_khong_mon " +
                           "FROM xt_giathuong WHERE TRIM(cccd) = TRIM(:cccd) LIMIT 1";

            Object[] gtData = (Object[]) session.createNativeQuery(sqlGT)
                    .setParameter("cccd", cccd)
                    .uniqueResult();

            if (gtData != null) {
                String maMon = (String) gtData[0];
                double dCoMon = ((Number) gtData[1]).doubleValue();
                double dKhongMon = ((Number) gtData[2]).doubleValue();

                if (toHopMonDaChon != null) {
                    String m1 = toHopMonDaChon.getMon1();
                    String m2 = toHopMonDaChon.getMon2();
                    String m3 = toHopMonDaChon.getMon3();

                    diemGT = (maMon.equals(m1) || maMon.equals(m2) || maMon.equals(m3))
                            ? dCoMon : dKhongMon;
                } else {
                    diemGT = dKhongMon;
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        // ===== 3. HIỂN THỊ =====
        txtDiemCC.setText(String.valueOf(diemCC));     // ✅ CHỈ CC
        txtDiemUTXT.setText(String.valueOf(diemGT));   // ✅ UTXT

        // ===== TỔNG =====
        double tongCong = Math.min(diemCC + diemGT, 3.0);
        txtDiemTong.setText(String.valueOf(tongCong)); // ✅ tổng
    }
    // Hàm bổ trợ lấy điểm từ Entity diemThi dựa trên mã môn (Toán, Lý, Hóa...)
    private double layDiemTheoMaMon(Entity.diemThiETT dt, String maMon) {
        if (maMon == null || dt == null) return 0.0;
        // Huy kiểm tra xem trong Entity diemThiETT dùng getTo() hay getT1() nhé
        switch (maMon) {
            case "TO": case "T1": return dt.getTo() != null ? dt.getTo() : 0.0;
            case "LI": case "L1": return dt.getLi() != null ? dt.getLi() : 0.0;
            case "HO": case "H1": return dt.getHo() != null ? dt.getHo() : 0.0;
            case "SI": case "S1": return dt.getSi() != null ? dt.getSi() : 0.0;
            case "SU": case "S2": return dt.getSu() != null ? dt.getSu() : 0.0;
            case "DI": case "D1": return dt.getDi() != null ? dt.getDi() : 0.0;
            case "VA": case "V1": return dt.getVa() != null ? dt.getVa() : 0.0;
            default: return 0.0;
        }
    }
    /**
     * @param args the command line arguments
     */
    public boolean isXacNhan() {
        return xacNhan;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonMaNganh;
    private javax.swing.JButton btnChonMaToHop;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCccd;
    private javax.swing.JTextField txtDiemCC;
    private javax.swing.JTextField txtDiemTong;
    private javax.swing.JTextField txtDiemUTXT;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaNganh;
    private javax.swing.JTextField txtMaToHop;
    // End of variables declaration//GEN-END:variables
}
