/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FUNC_GUI;

import Entity.chungChiETT;
import BUS.chungChiBUS;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Dat
 */
public class updateChungChi extends javax.swing.JDialog {
    public boolean xacNhan = false;
    private chungChiETT chungChi; // Đối tượng lưu trữ dữ liệu hiện tại
    private chungChiBUS bus = new chungChiBUS();
    // Contructor
    public updateChungChi(java.awt.Frame parent, boolean modal, chungChiETT data) {
        super(parent, modal);
        initComponents();
        this.chungChi = data;
        setLocationRelativeTo(parent);

        // 1. Khóa các ô không nên sửa khi cập nhật (như CCCD)
        txtCCCD.setText(data.getCccd());
        txtCCCD.setEditable(false); 
        txtDiemQuyDoi.setEditable(false);
        txtDiemCong.setEditable(false);

        // 2. Đổ dữ liệu cũ lên các thành phần điều khiển
        cboLoaiChungChi.setSelectedItem(data.getLoaiChungChi());
        txtDiemQuyDoi.setText(String.valueOf(data.getDiemQuyDoi()));
        txtDiemCong.setText(String.valueOf(data.getDiemCong()));

        // 3. Xử lý hiển thị Panel và phân rã điểm
        String loai = data.getLoaiChungChi();
        String diemGoc = data.getDiemChungChi();

        if (loai.equals("Tiếng Anh - TOEIC (4 kỹ năng)")) {
            pnlNormal.setVisible(false);
            pnlToeic4.setVisible(true);
            
            // Phân rã chuỗi "Nghe/Đọc/Nói/Viết" để điền vào 4 ô
            String[] scores = diemGoc.split("/");
            if (scores.length == 4) {
                txtNghe.setText(scores[0]);
                txtDoc.setText(scores[1]);
                txtNoi.setText(scores[2]);
                txtViet.setText(scores[3]);
            }
        } else {
            pnlNormal.setVisible(true);
            pnlToeic4.setVisible(false);
            txtDiemChungChi.setText(diemGoc);
        }
        
        this.pack(); // Co giãn giao diện cho vừa khít
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        cboLoaiChungChi = new javax.swing.JComboBox<>();
        txtDiemQuyDoi = new javax.swing.JTextField();
        txtDiemCong = new javax.swing.JTextField();
        btnChonCCCDThiSinh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlNormal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDiemChungChi = new javax.swing.JTextField();
        pnlToeic4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNghe = new javax.swing.JTextField();
        txtNoi = new javax.swing.JTextField();
        txtDoc = new javax.swing.JTextField();
        txtViet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Sửa Chứng Chỉ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lý thêm Chứng Chỉ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setToolTipText("");

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(this::btnThemActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm Chứng Chỉ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("CCCD Thí Sinh");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Loại chứng chỉ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Điểm quy đổi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Điểm cộng");

        txtCCCD.setBackground(new java.awt.Color(246, 246, 246));
        txtCCCD.addActionListener(this::txtCCCDActionPerformed);

        cboLoaiChungChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Anh - IELTS", "Tiếng Anh - TOEFL ITP", "Tiếng Anh - TOEFL iBT", "Tiếng Anh - TOEIC (4 kỹ năng)", "Tiếng Anh - PTE Academic (Pearson)", "Tiếng Anh - Linguaskill", "Tiếng Anh - Aptis ESOL (General)", "Tiếng Anh - Aptis ESOL (Advanced)", "Tiếng Anh - VSTEP (tối thiểu bậc 3)" }));
        cboLoaiChungChi.addActionListener(this::cboLoaiChungChiActionPerformed);

        txtDiemQuyDoi.setEditable(false);
        txtDiemQuyDoi.addActionListener(this::txtDiemQuyDoiActionPerformed);

        txtDiemCong.setEditable(false);
        txtDiemCong.addActionListener(this::txtDiemCongActionPerformed);

        btnChonCCCDThiSinh.setText("...");
        btnChonCCCDThiSinh.setToolTipText("");
        btnChonCCCDThiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlNormal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Điểm chứng chỉ");

        txtDiemChungChi.setBackground(new java.awt.Color(246, 246, 246));
        txtDiemChungChi.setColumns(18);
        txtDiemChungChi.addCaretListener(this::txtDiemChungChiCaretUpdate);
        txtDiemChungChi.addActionListener(this::txtDiemChungChiActionPerformed);

        javax.swing.GroupLayout pnlNormalLayout = new javax.swing.GroupLayout(pnlNormal);
        pnlNormal.setLayout(pnlNormalLayout);
        pnlNormalLayout.setHorizontalGroup(
            pnlNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiemChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNormalLayout.setVerticalGroup(
            pnlNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(txtDiemChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlToeic4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nghe");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nói");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đọc");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Viết");

        txtNghe.setBackground(new java.awt.Color(246, 246, 246));
        txtNghe.addCaretListener(this::txtNgheCaretUpdate);

        txtNoi.setBackground(new java.awt.Color(246, 246, 246));
        txtNoi.addCaretListener(this::txtNoiCaretUpdate);

        txtDoc.setBackground(new java.awt.Color(246, 246, 246));
        txtDoc.addCaretListener(this::txtDocCaretUpdate);

        txtViet.setBackground(new java.awt.Color(246, 246, 246));
        txtViet.addCaretListener(this::txtVietCaretUpdate);

        javax.swing.GroupLayout pnlToeic4Layout = new javax.swing.GroupLayout(pnlToeic4);
        pnlToeic4.setLayout(pnlToeic4Layout);
        pnlToeic4Layout.setHorizontalGroup(
            pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToeic4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlToeic4Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtViet, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlToeic4Layout.createSequentialGroup()
                            .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlToeic4Layout.setVerticalGroup(
            pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToeic4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToeic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtViet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlToeic4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlToeic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiChungChi, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChonCCCDThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonCCCDThiSinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLoaiChungChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemQuyDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiemCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        xacNhan = false;
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String loaiCC = cboLoaiChungChi.getSelectedItem().toString();
        String diemGoc = loaiCC.equals("Tiếng Anh - TOEIC (4 kỹ năng)") 
                         ? (txtNghe.getText() + "/" + txtDoc.getText() + "/" + txtNoi.getText() + "/" + txtViet.getText())
                         : txtDiemChungChi.getText().trim();

        try {
            // Cập nhật lại các thuộc tính cho đối tượng chungChi hiện tại
            chungChi.setLoaiChungChi(loaiCC);
            chungChi.setDiemChungChi(diemGoc);
            chungChi.setDiemQuyDoi(Double.parseDouble(txtDiemQuyDoi.getText()));
            chungChi.setDiemCong(Double.parseDouble(txtDiemCong.getText()));

            // Gọi BUS để thực hiện UPDATE xuống Database
            if (bus.suaCC(chungChi)) { // Giả sử Đạt đã viết hàm update trong BUS
                xacNhan = true;
                JOptionPane.showMessageDialog(this, "Cập nhật chứng chỉ thành công!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    public chungChiETT getChungChi() {
        return chungChi;
    }
    
    public boolean isXacNhan() { 
        return xacNhan; 
    }
    
    private void txtDiemCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemCongActionPerformed

    private void txtDiemQuyDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemQuyDoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemQuyDoiActionPerformed

    private void cboLoaiChungChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiChungChiActionPerformed
        // TODO add your handling code here:
        String selected = cboLoaiChungChi.getSelectedItem().toString();

        if (selected.equals("Tiếng Anh - TOEIC (4 kỹ năng)")) {
            pnlNormal.setVisible(false);
            pnlToeic4.setVisible(true);
            // Reset điểm khi chuyển sang TOEIC
            txtDiemQuyDoi.setText("0");
            txtDiemCong.setText("0");
        } else {
            pnlNormal.setVisible(true);
            pnlToeic4.setVisible(false);
        }
        tinhToanDiem(); // Tính lại ngay khi đổi loại
        this.pack();
    }//GEN-LAST:event_cboLoaiChungChiActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void txtNgheCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNgheCaretUpdate
        // TODO add your handling code here:
        updateResultToeic4();
    }//GEN-LAST:event_txtNgheCaretUpdate

    private void txtDocCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDocCaretUpdate
        // TODO add your handling code here:
        updateResultToeic4();
    }//GEN-LAST:event_txtDocCaretUpdate

    private void txtNoiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoiCaretUpdate
        // TODO add your handling code here:
        updateResultToeic4();
    }//GEN-LAST:event_txtNoiCaretUpdate

    private void txtVietCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtVietCaretUpdate
        // TODO add your handling code here:
        updateResultToeic4();
    }//GEN-LAST:event_txtVietCaretUpdate

    private void txtDiemChungChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemChungChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemChungChiActionPerformed

    private void txtDiemChungChiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDiemChungChiCaretUpdate
        // TODO add your handling code here:
        tinhToanDiem();
    }//GEN-LAST:event_txtDiemChungChiCaretUpdate

//    private void loadDataToCboDiemPhuThuoc(String certName) {
//        cboDiemChungChi.removeAllItems();
//        if (certificateData.containsKey(certName)) {
//            for (String score : certificateData.get(certName)) {
//                cboDiemChungChi.addItem(score);
//            }
//        }
//    }
    
    private void updateResultToeic4() {
    try {
        // Lấy giá trị từ 4 ô (nhớ check empty)
        if(txtNghe.getText().isEmpty() || txtDoc.getText().isEmpty() || 
           txtNoi.getText().isEmpty() || txtViet.getText().isEmpty()) {
           txtDiemQuyDoi.setText("0");
           txtDiemCong.setText("0");
           return;
        }
        
        int n = Integer.parseInt(txtNghe.getText());
        int d = Integer.parseInt(txtDoc.getText());
        int s = Integer.parseInt(txtNoi.getText());
        int w = Integer.parseInt(txtViet.getText());

        // Logic Math.min như đã bàn
        int levelNghe = (n >= 490) ? 10 : (n >= 400) ? 9 : (n >= 275) ? 8 : 0;
        int levelDoc  = (d >= 455) ? 10 : (d >= 385) ? 9 : (d >= 275) ? 8 : 0;
        int levelNoi  = (s >= 180) ? 10 : (s >= 160) ? 9 : (s >= 120) ? 8 : 0;
        int levelViet = (w >= 180) ? 10 : (w >= 150) ? 9 : (w >= 120) ? 8 : 0;

        int finalLevel = Math.min(Math.min(levelNghe, levelDoc), Math.min(levelNoi, levelViet));
        
        txtDiemQuyDoi.setText(String.valueOf(finalLevel));
        double bonus = (finalLevel == 10) ? 2.0 : (finalLevel == 9) ? 1.5 : (finalLevel == 8) ? 1.0 : 0;
        txtDiemCong.setText(String.valueOf(bonus));
    } catch (NumberFormatException e) {
        // Tránh lỗi khi user gõ chữ
    }
}

    // Hàm 1: Kiểm tra ô TOEIC có trống không
    private boolean checkEmptyToeic() {
        return txtNghe.getText().trim().isEmpty() || txtDoc.getText().trim().isEmpty() || 
               txtNoi.getText().trim().isEmpty() || txtViet.getText().trim().isEmpty();
    }

// Hàm 2: Tự động tính điểm (Cái này mình đã viết ở câu trước, Đạt dán vào đây)
private void tinhToanDiem() {
    String loai = cboLoaiChungChi.getSelectedItem().toString();
    double qd = 0; 
    double cg = 0; 
    String cccd = txtCCCD.getText().trim();

    try {
        if (loai.equals("Tiếng Anh - TOEIC (4 kỹ năng)")) {
            if(txtNghe.getText().isEmpty() || txtDoc.getText().isEmpty()) return;
            // Ép kiểu số cho 4 kỹ năng TOEIC
            int n = Integer.parseInt(txtNghe.getText().trim());
            int d = Integer.parseInt(txtDoc.getText().trim());
            int s = Integer.parseInt(txtNoi.getText().trim());
            int w = Integer.parseInt(txtViet.getText().trim());
            
            int levelNghe = (n >= 490) ? 10 : (n >= 400) ? 9 : (n >= 275) ? 8 : 0;
            int levelDoc  = (d >= 455) ? 10 : (d >= 385) ? 9 : (d >= 275) ? 8 : 0;
            int levelNoi  = (s >= 180) ? 10 : (s >= 160) ? 9 : (s >= 120) ? 8 : 0;
            int levelViet = (w >= 180) ? 10 : (w >= 150) ? 9 : (w >= 120) ? 8 : 0;
            qd = Math.min(Math.min(levelNghe, levelDoc), Math.min(levelNoi, levelViet));
        } 
        else {
            // LẤY TỪ Ô TEXTFIELD MỚI ĐỔI TÊN
            String input = txtDiemChungChi.getText().trim();
            if(input.isEmpty()) return;

            if (loai.equals("Tiếng Anh - IELTS")) {
                double v = Double.parseDouble(input);
                qd = (v >= 7.0) ? 10 : (v >= 5.5) ? 9 : (v >= 4.0) ? 8 : 0;
            } 
            else if (loai.equals("Tiếng Anh - TOEFL ITP")) {
                int v = Integer.parseInt(input);
                qd = (v >= 627) ? 10 : (v >= 500) ? 9 : (v >= 450) ? 8 : 0;
            }
            else if (loai.equals("Tiếng Anh - VSTEP")) {
                if (input.contains("5")) qd = 10;
                else if (input.contains("4")) qd = 9;
                else if (input.contains("3")) qd = 8;
            }
            // Thêm các case TOEFL iBT, PTE... tương tự
        }

        // Tính điểm quy đổi và cộng (Logic cũ)
        if (qd == 10) cg = 2.0;
        else if (qd == 9) cg = 1.5;
        else if (qd == 8) cg = 1.0;

        txtDiemQuyDoi.setText(String.valueOf(qd));
        
        // chungChiBUS bus = new chungChiBUS();
        if (bus.checkToHopCoMonAnh(txtCCCD.getText().trim())) {
                txtDiemCong.setText("0.0");
        } else {
            txtDiemCong.setText(String.valueOf(cg));
        }

    } catch (Exception e) {
        txtDiemQuyDoi.setText("0");
        txtDiemCong.setText("0");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonCCCDThiSinh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboLoaiChungChi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlNormal;
    private javax.swing.JPanel pnlToeic4;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiemChungChi;
    private javax.swing.JTextField txtDiemCong;
    private javax.swing.JTextField txtDiemQuyDoi;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtNghe;
    private javax.swing.JTextField txtNoi;
    private javax.swing.JTextField txtViet;
    // End of variables declaration//GEN-END:variables
}
